name: Cool CHECK

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      ABC: ${{ github.ref_name }}
      ABC2: ${{ github.ref_name }}-${{ github.ref_name }}-1.2.3.4
    steps:
      - name: Echo
        run: |
          echo "ABC: $ABC"
          echo "ABC2: $ABC2"
