name: Cool CI

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Version to checkout
        run: |
          echo "Version to checkout: ${{ github.event.client_payload.version }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.client_payload.version }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Print pyproject
        run: cat pyproject.toml
